name: Benchmark And Profiling

on:
  pull_request:
    branches: [main, dev]

env:
  SETUP_PY: ./
  BENCHMARK_OUTPUT: benchmark.json
  PROFILING_OUTPUT: profile.out
  SIMULATION_SCRIPT: ./scripts/tools/python/profiling_script.py
  DEV_REQUIREMENTS: ./scripts/configs/dev_requirements.txt
  PYTHON_VERSION: "3.11"

jobs:
  set-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-matrix.outputs.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Runner
        id: set-matrix
        uses: ./.github/actions/utils/determine-runner

  benchmark:
    needs: set-runner
    runs-on: ${{ needs.set-runner.outputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Linux testing environment
        uses: ./.github/actions/setup/linux-testing-environment
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          setup-path: ${{ env.SETUP_PY }}
          dev-requirements: ${{ env.DEV_REQUIREMENTS }}
          extra-packages: "pytest"
          checkout: "false"

      - name: Run benchmarks
        run: |
          pytest --benchmark-only --benchmark-save=${{ env.BENCHMARK_OUTPUT }}

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: ${{ env.BENCHMARK_OUTPUT }}

  profiling:
    name: "Profiling: Simulation Experiment"
    needs: [set-runner, benchmark]
    runs-on: ${{ needs.set-runner.outputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Linux testing environment
        uses: ./.github/actions/setup/linux-testing-environment
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          setup-path: ${{ env.SETUP_PY }}
          dev-requirements: ${{ env.DEV_REQUIREMENTS }}
          checkout: "false"

      - name: Run profiling with cProfile
        run: |
          python -m cProfile -o ${{ env.PROFILING_OUTPUT }} ${{ env.SIMULATION_SCRIPT }}

      - name: Upload profiling results
        uses: actions/upload-artifact@v4
        with:
          name: profiling-results
          path: ${{ env.PROFILING_OUTPUT }}
