name: GitHub Pages

on:
  pull_request:
    branches: [main, dev]

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      proceed: ${{ steps.branch-check.outputs.proceed }}
    steps:
      - name: Check PR Source Branch
        id: branch-check
        run: |
          FROM_BRANCH="${{ github.head_ref }}"
          if [[ "$FROM_BRANCH" != "dev" && "$FROM_BRANCH" != "release" && ! "$FROM_BRANCH" =~ "test-workflow" ]]; then
            echo "This workflow only runs for PRs from branches named 'dev', 'release', or containing 'test-workflow'. Exiting gracefully."
            echo "proceed=false" >> $GITHUB_OUTPUT
            echo "proceed=false" >> $GITHUB_ENV
            exit 0
          fi
          echo "proceed=true" >> $GITHUB_OUTPUT
          echo "proceed=true" >> $GITHUB_ENV

  set-runner:
    needs: validate-branch
    if: needs.validate-branch.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-matrix.outputs.runner }}
    steps:
      - name: Determine Runner
        id: set-matrix
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ "$BRANCH" =~ test-workflow ]]; then
          echo "runner=self-hosted" >> $GITHUB_ENV
          echo "runner=self-hosted" >> $GITHUB_OUTPUT
          else
          echo "runner=ubuntu-latest" >> $GITHUB_ENV
          echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          fi
          echo "Using runner: $GITHUB_ENV"

  build:
    needs: set-runner
    continue-on-error: true
    runs-on: ${{ needs.set-runner.outputs.runner }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary requirements file
        run: |
          touch docs/final_doc_requirements.txt
          [ -f docs/doc_requirements.txt ] && cat docs/doc_requirements.txt >> docs/final_doc_requirements.txt && echo "" >> docs/final_doc_requirements.txt
          [ -f configs/requirements.txt ] && cat configs/requirements.txt >> docs/final_doc_requirements.txt && echo "" >> docs/final_doc_requirements.txt

      - id: build
        uses: sphinx-notes/pages@v3
        with:
          requirements_path: "./docs/final_doc_requirements.txt"
          python_version: "3.11"
          sphinx_version: "7.4.7"
          checkout: false

  deploy:
    continue-on-error: true
    needs: [set-runner, build]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ${{ needs.set-runner.outputs.runner }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
